-- Create Job Applications Table
create table job_applications (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  company text not null,
  role text not null,
  status text check (status in ('Applied', 'Interview', 'Offer', 'Rejected')) default 'Applied',
  salary text,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table job_applications enable row level security;

-- Create Policy: Users can only see their own data
create policy "Users can view own job applications"
  on job_applications for select
  using ( auth.uid() = user_id );

-- Create Policy: Users can insert their own data
create policy "Users can insert own job applications"
  on job_applications for insert
  with check ( auth.uid() = user_id );

-- Create Policy: Users can update their own data
create policy "Users can update own job applications"
  on job_applications for update
  using ( auth.uid() = user_id );

-- Create Policy: Users can delete their own data
-- Create Policy: Users can delete their own job applications
create policy "Users can delete own job applications"
  on job_applications for delete
  using ( auth.uid() = user_id );

-- Create CVs Table
create table cvs (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users not null,
  content jsonb not null default '{}'::jsonb,
  is_public boolean default false,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for CVs
alter table cvs enable row level security;

-- Policy: Users can view their own CVs
create policy "Users can view own cvs"
  on cvs for select
  using ( auth.uid() = user_id );

-- Policy: Public can view public CVs
create policy "Public can view public cvs"
  on cvs for select
  using ( is_public = true );

-- Policy: Users can insert their own CVs
create policy "Users can insert own cvs"
  on cvs for insert
  with check ( auth.uid() = user_id );

-- Policy: Users can update their own CVs
create policy "Users can update own cvs"
  on cvs for update
  using ( auth.uid() = user_id );

-- Policy: Users can delete their own CVs
create policy "Users can delete own cvs"
  on cvs for delete
  using ( auth.uid() = user_id );

-- Create User Credits Table
create table user_credits (
  user_id uuid references auth.users not null primary key,
  balance int default 0 not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table user_credits enable row level security;

create policy "Users can view own credits"
  on user_credits for select
  using ( auth.uid() = user_id );

create policy "Users can update own credits" -- Ideally backend only, but for demo:
  on user_credits for update
  using ( auth.uid() = user_id );

create policy "Users can insert own credits"
  on user_credits for insert
  with check ( auth.uid() = user_id );

-- Function to increment credits
create or replace function increment_credits(user_id uuid, amount int)
returns void as $$
begin
  insert into user_credits (user_id, balance)
  values (user_id, amount)
  on conflict (user_id)
  do update set balance = user_credits.balance + amount;
end;
$$ language plpgsql security definer;
